name: CustomJoinMessage
version: '1.2-FINAL'
main: skyxnetwork.customJoinMessage.CustomJoinMessage.CustomJoinMessage
api-version: '1.20'
description: A plugin to manage custom join/leave messages.
commands:
  joinmessage:
    description: Manage custom join/leave messages.
    usage: /joinmessage [set/reset/show/reload] [join/leave/playername] [message]
    aliases: [ jm ]
permissions:
  skyxnetwork.joinmessage.set:
    description: Allows players to set a custom join or leave message.
    default: op
  skyxnetwork.joinmessage.reset:
    description: Allows players to reset their custom join or leave messages.
    default: op
  skyxnetwork.joinmessage.show:
    description: Allows players to view custom join/leave messages for a specific player.
    default: op
  skyxnetwork.joinmessage.reload:
    description: Allows reloading the configuration and userdata.
    default: op